# Generated by Django 3.2.8 on 2023-07-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click above to read blog post', max_length=255),
        ),
    ]
